version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:PoPo1234@database:5432/UAVThreatDetectorDB
    depends_on:
      - database
    links:
      - database
  
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  
  database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PoPo1234
      POSTGRES_DB: UAVThreatDetectorDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    name: UTD_network